'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DownloadDir() As String
            Get
                Return CType(Me("DownloadDir"),String)
            End Get
            Set
                Me("DownloadDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("English")>  _
        Public Property Langue() As String
            Get
                Return CType(Me("Langue"),String)
            End Get
            Set
                Me("Langue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("David Shaw Informatique Sàrl")>  _
        Public Property AuthorName() As String
            Get
                Return CType(Me("AuthorName"),String)
            End Get
            Set
                Me("AuthorName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("saadry.dunkel@ds-informatique.ch")>  _
        Public Property AuthorEmail() As String
            Get
                Return CType(Me("AuthorEmail"),String)
            End Get
            Set
                Me("AuthorEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.ds-informatique.ch")>  _
        Public Property AuthorUrl() As String
            Get
                Return CType(Me("AuthorUrl"),String)
            End Get
            Set
                Me("AuthorUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property Price_Import() As Double
            Get
                Return CType(Me("Price_Import"),Double)
            End Get
            Set
                Me("Price_Import") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.8")>  _
        Public Property Price_Property() As Double
            Get
                Return CType(Me("Price_Property"),Double)
            End Get
            Set
                Me("Price_Property") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property Price_Enumeration() As Double
            Get
                Return CType(Me("Price_Enumeration"),Double)
            End Get
            Set
                Me("Price_Enumeration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property Price_Structure() As Double
            Get
                Return CType(Me("Price_Structure"),Double)
            End Get
            Set
                Me("Price_Structure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.2")>  _
        Public Property Price_Sub() As Double
            Get
                Return CType(Me("Price_Sub"),Double)
            End Get
            Set
                Me("Price_Sub") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.6")>  _
        Public Property Price_Function() As Double
            Get
                Return CType(Me("Price_Function"),Double)
            End Get
            Set
                Me("Price_Function") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property Price_Runtime() As Double
            Get
                Return CType(Me("Price_Runtime"),Double)
            End Get
            Set
                Me("Price_Runtime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.8")>  _
        Public Property Price_Loader() As Double
            Get
                Return CType(Me("Price_Loader"),Double)
            End Get
            Set
                Me("Price_Loader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property Price_Class() As Double
            Get
                Return CType(Me("Price_Class"),Double)
            End Get
            Set
                Me("Price_Class") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.4")>  _
        Public Property Price_Constante() As Double
            Get
                Return CType(Me("Price_Constante"),Double)
            End Get
            Set
                Me("Price_Constante") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.2")>  _
        Public Property Price_Events() As Double
            Get
                Return CType(Me("Price_Events"),Double)
            End Get
            Set
                Me("Price_Events") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("523.5")>  _
        Public Property Price_DataBase() As Double
            Get
                Return CType(Me("Price_DataBase"),Double)
            End Get
            Set
                Me("Price_DataBase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("116.5")>  _
        Public Property Price_Table() As Double
            Get
                Return CType(Me("Price_Table"),Double)
            End Get
            Set
                Me("Price_Table") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("309.5")>  _
        Public Property Price_Fichier() As Double
            Get
                Return CType(Me("Price_Fichier"),Double)
            End Get
            Set
                Me("Price_Fichier") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property Price_Parameter() As Double
            Get
                Return CType(Me("Price_Parameter"),Double)
            End Get
            Set
                Me("Price_Parameter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property Price_Member() As Double
            Get
                Return CType(Me("Price_Member"),Double)
            End Get
            Set
                Me("Price_Member") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.077")>  _
        Public Property VAT() As Double
            Get
                Return CType(Me("VAT"),Double)
            End Get
            Set
                Me("VAT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Century Gothic, 11.25pt")>  _
        Public Property Font() As Global.System.Drawing.Font
            Get
                Return CType(Me("Font"),Global.System.Drawing.Font)
            End Get
            Set
                Me("Font") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft.ACE.OLEDB.12.0")>  _
        Public Property Adaptor_Accdb() As String
            Get
                Return CType(Me("Adaptor_Accdb"),String)
            End Get
            Set
                Me("Adaptor_Accdb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft.Jet.OLEDB.4.0")>  _
        Public Property Adaptor_Dbf() As String
            Get
                Return CType(Me("Adaptor_Dbf"),String)
            End Get
            Set
                Me("Adaptor_Dbf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft.ACE.OLEDB.12.0")>  _
        Public Property Adaptor_Excel() As String
            Get
                Return CType(Me("Adaptor_Excel"),String)
            End Get
            Set
                Me("Adaptor_Excel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft.Jet.OLEDB.4.0")>  _
        Public Property Adaptor_Mdb() As String
            Get
                Return CType(Me("Adaptor_Mdb"),String)
            End Get
            Set
                Me("Adaptor_Mdb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft.ACE.OLEDB.12.0")>  _
        Public Property Adaptor_Saadry() As String
            Get
                Return CType(Me("Adaptor_Saadry"),String)
            End Get
            Set
                Me("Adaptor_Saadry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Counter() As Integer
            Get
                Return CType(Me("Counter"),Integer)
            End Get
            Set
                Me("Counter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Extended Properties")>  _
        Public Property Dbf_ExtendedProperty_0() As String
            Get
                Return CType(Me("Dbf_ExtendedProperty_0"),String)
            End Get
            Set
                Me("Dbf_ExtendedProperty_0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dBase III")>  _
        Public Property Dbf_ExtendedProperty_1() As String
            Get
                Return CType(Me("Dbf_ExtendedProperty_1"),String)
            End Get
            Set
                Me("Dbf_ExtendedProperty_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Extended Properties")>  _
        Public Property Excel_Ext1() As String
            Get
                Return CType(Me("Excel_Ext1"),String)
            End Get
            Set
                Me("Excel_Ext1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Excel 12.0 Xml")>  _
        Public Property Excel_Ext2() As String
            Get
                Return CType(Me("Excel_Ext2"),String)
            End Get
            Set
                Me("Excel_Ext2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HDR=YES")>  _
        Public Property Excel_Ext3() As String
            Get
                Return CType(Me("Excel_Ext3"),String)
            End Get
            Set
                Me("Excel_Ext3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HasConnection() As Boolean
            Get
                Return CType(Me("HasConnection"),Boolean)
            End Get
            Set
                Me("HasConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dunke92606!")>  _
        Public Property Key() As String
            Get
                Return CType(Me("Key"),String)
            End Get
            Set
                Me("Key") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.0")>  _
        Public Property LAN() As String
            Get
                Return CType(Me("LAN"),String)
            End Get
            Set
                Me("LAN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Jet OLEDB:Database Password")>  _
        Public Property OleDbSetPassword() As String
            Get
                Return CType(Me("OleDbSetPassword"),String)
            End Get
            Set
                Me("OleDbSetPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.1.0")>  _
        Public Property Routeur() As String
            Get
                Return CType(Me("Routeur"),String)
            End Get
            Set
                Me("Routeur") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Saphire")>  _
        Public Property Server() As String
            Get
                Return CType(Me("Server"),String)
            End Get
            Set
                Me("Server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Speak() As Boolean
            Get
                Return CType(Me("Speak"),Boolean)
            End Get
            Set
                Me("Speak") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=")>  _
        Public Property Sql_DataSource() As String
            Get
                Return CType(Me("Sql_DataSource"),String)
            End Get
            Set
                Me("Sql_DataSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8.8.8.8")>  _
        Public Property Web() As String
            Get
                Return CType(Me("Web"),String)
            End Get
            Set
                Me("Web") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Office2007VistaGlass")>  _
        Public Property Style() As Global.DevComponents.DotNetBar.eStyle
            Get
                Return CType(Me("Style"),Global.DevComponents.DotNetBar.eStyle)
            End Get
            Set
                Me("Style") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("26, 97, 139")>  _
        Public Property ManagerColorTint() As Global.System.Drawing.Color
            Get
                Return CType(Me("ManagerColorTint"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ManagerColorTint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property CanvasColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("CanvasColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("CanvasColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("43, 87, 154")>  _
        Public Property BaseColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("BaseColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("BaseColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultOuput() As String
            Get
                Return CType(Me("DefaultOuput"),String)
            End Get
            Set
                Me("DefaultOuput") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Copyright on SmartOffice programming tools.All rights, including those for reprod"& _ 
            "uction, reprinting and translation of training materials are the property of Dav"& _ 
            "id Shaw Informatique Sàrl or the specified supplier. The"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"training materials may"& _ 
            " not be reproduced in any form, used for academic purposes, or used for public"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "without the prior written permission of David Shaw Informatique Sàrl.The softwar"& _ 
            "e, components and data used in the course are protected by copyright and should "& _ 
            "not be copied on any media or"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"taken out of the classroom.")>  _
        Public Property SummaryRights() As String
            Get
                Return CType(Me("SummaryRights"),String)
            End Get
            Set
                Me("SummaryRights") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property SpeechVolume() As Double
            Get
                Return CType(Me("SpeechVolume"),Double)
            End Get
            Set
                Me("SpeechVolume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SpeechRate() As Double
            Get
                Return CType(Me("SpeechRate"),Double)
            End Get
            Set
                Me("SpeechRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("134.5")>  _
        Public Property Price_Folder() As Double
            Get
                Return CType(Me("Price_Folder"),Double)
            End Get
            Set
                Me("Price_Folder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35.5")>  _
        Public Property Price_LineInfo() As Double
            Get
                Return CType(Me("Price_LineInfo"),Double)
            End Get
            Set
                Me("Price_LineInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dunke92606!")>  _
        Public Property Cypher() As String
            Get
                Return CType(Me("Cypher"),String)
            End Get
            Set
                Me("Cypher") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("29.5")>  _
        Public Property Price_RetrieveIcons() As Double
            Get
                Return CType(Me("Price_RetrieveIcons"),Double)
            End Get
            Set
                Me("Price_RetrieveIcons") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("36.5")>  _
        Public Property Price_SizeInfo() As Double
            Get
                Return CType(Me("Price_SizeInfo"),Double)
            End Get
            Set
                Me("Price_SizeInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2.5")>  _
        Public Property Marge() As Double
            Get
                Return CType(Me("Marge"),Double)
            End Get
            Set
                Me("Marge") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Db_Empty_Compta_FilePath() As String
            Get
                Return CType(Me("Db_Empty_Compta_FilePath"),String)
            End Get
            Set
                Me("Db_Empty_Compta_FilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Db_Empty_Compta_Password() As String
            Get
                Return CType(Me("Db_Empty_Compta_Password"),String)
            End Get
            Set
                Me("Db_Empty_Compta_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Db_Empty_Compta_Line() As String
            Get
                Return CType(Me("Db_Empty_Compta_Line"),String)
            End Get
            Set
                Me("Db_Empty_Compta_Line") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MusicFolder() As String
            Get
                Return CType(Me("MusicFolder"),String)
            End Get
            Set
                Me("MusicFolder") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SmartCoder.My.MySettings
            Get
                Return Global.SmartCoder.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
